## CM50266 Applied Data Science (Case Study – Tesco Grocery 1.0 Dataset vs. Income)

#### Objective:
This code file is used to prepare the data for creating the visualization. However, those visualizations will be created in MS Excel after this. 

#### Tasks: 
- Two insights will need to be extracted from [Tesco Grocery 1.0 Dataset](https://figshare.com/collections/Tesco_Grocery_1_0/4769354) and visualisations will be created to represent them. First research question is "How gender and age impact to purchased product category?" and second reseach question is "How different in each category purchases based on areas with high and low purchases of fruit and vegetable?"
- Extract insight from income data: [Regional gross disposable household income: local authorities by ITL1 region](https://www.ons.gov.uk/economy/regionalaccounts/grossdisposablehouseholdincome/datasets/regionalgrossdisposablehouseholdincomelocalauthoritiesbyitl1region) and visualize it.
- Extract correlation or non-correlation from both dataset by referencing the finding from [US Adults' Fruit and Vegetable Intakes,1989 to 1991: A Revised Baseline for the Healthy People 2000 Objective](https://ajph.aphapublications.org/doi/pdf/10.2105/AJPH.85.12.1623). 

#### References:
- Tesco 1.0 Dataset - https://figshare.com/collections/Tesco_Grocery_1_0/4769354
- Regional gross disposable household income Dataset - https://www.ons.gov.uk/economy/regionalaccounts/grossdisposablehouseholdincome/datasets/regionalgrossdisposablehouseholdincomelocalauthoritiesbyitl1region
- US Adults' Fruit and Vegetable Intakes,1989 to 1991: A Revised Baseline for the Healthy People 2000 Objective - https://ajph.aphapublications.org/doi/pdf/10.2105/AJPH.85.12.1623

In [1]:
# Import related libraries

import os
import numpy
import pandas
import seaborn
import geopandas
import plotly.express
import matplotlib.pyplot

# Disable warning
import warnings
warnings.filterwarnings("ignore")

In [2]:
# TESCO 1.0 DATASET

# Declare vars
folder_path = "/Users/rasitapkr/Documents/MSc Data Science/Applied Data Science/Coursework Sem 2/Datasets/"
folder_path_groceriespurchased = folder_path + "Area-level grocery purchases/"

# Get annual data from file and add to dataframe

annual_data_groceriespurchased_borough = pandas.DataFrame([])
annual_data_groceriespurchased_borough = pandas.read_csv(folder_path_groceriespurchased + "year_borough_grocery.csv", skipinitialspace = True)
display(annual_data_groceriespurchased_borough)

,area_id,weight,weight_perc2.5,weight_perc25,weight_perc50,weight_perc75,weight_perc97.5,weight_std,weight_ci95,volume,...,man_day,population,male,female,age_0_17,age_18_64,age_65+,avg_age,area_sq_km,people_per_sq_km
0,E09000001,323.174750,35.0,150.0,250.0,400.0,1000.0,323.692596,1.001520,98.842963,...,103883,6687.0,3697.0,2990.0,1018.0,4349.0,1320.0,43.910124,2.90,2305.862069
1,E09000002,421.304125,32.5,165.6,300.0,500.0,1500.0,597.994271,0.828993,122.341294,...,397127,203101.0,99442.0,103659.0,60281.0,123180.0,19640.0,33.017321,36.09,5627.625381
2,E09000003,407.170491,40.0,180.0,320.0,500.0,1160.0,443.644324,0.171615,114.933771,...,4131210,378778.0,186357.0,192421.0,88754.0,237036.0,52988.0,37.195582,86.76,4365.813739
3,E09000004,359.544126,30.0,144.0,255.0,450.0,1000.0,476.576945,0.819748,106.446426,...,380177,242387.0,116814.0,125573.0,56028.0,146237.0,40122.0,38.880749,60.58,4001.105976
4,E09000005,434.324141,40.0,175.0,325.0,500.0,1500.0,616.087316,0.354492,128.930369,...,2541113,323443.0,163939.0,159504.0,75033.0,211885.0,36525.0,35.766416,43.28,7473.267098
5,E09000006,319.336273,30.0,135.0,250.0,400.0,1000.0,347.979651,0.458224,101.105159,...,734232,325303.0,156274.0,169029.0,72176.0,196323.0,56804.0,39.853429,150.14,2166.664447
6,E09000007,348.420414,35.0,150.0,260.0,450.0,1000.0,370.640809,0.373270,102.525979,...,917661,243837.0,121808.0,122029.0,46242.0,169330.0,28265.0,35.934276,21.87,11149.382716
7,E09000008,353.636123,30.0,150.0,250.0,450.0,1000.0,425.267620,0.487412,107.461977,...,824237,380070.0,184305.0,195765.0,93166.0,237511.0,49393.0,36.896435,86.57,4390.319972
8,E09000009,358.569245,35.0,154.0,275.0,454.0,1000.0,373.797449,0.271506,106.197369,...,1824981,344285.0,172747.0,171538.0,81217.0,222669.0,40399.0,36.143460,55.55,6197.749775
9,E09000010,416.062456,40.0,180.0,325.0,500.0,1500.0,456.120381,0.187516,122.353062,...,3493012,328738.0,159756.0,168982.0,83274.0,203384.0,42080.0,36.190751,80.84,4066.526472
10,E09000011,403.189686,37.5,170.0,305.0,500.0,1200.0,498.743168,0.323224,114.736225,...,1795750,274542.0,137569.0,136973.0,66010.0,179854.0,28678.0,34.858641,47.39,5793.247521
11,E09000012,405.993196,40.0,175.0,308.0,500.0,1160.0,486.498044,0.296792,111.593823,...,1999259,268626.0,133429.0,135197.0,61120.0,188145.0,19361.0,32.973528,19.08,14078.930818
12,E09000013,368.873372,40.0,166.4,300.0,485.0,1000.0,355.888762,0.223326,102.882176,...,1879110,182183.0,89454.0,92729.0,34398.0,129350.0,18435.0,35.687814,16.40,11108.719512
13,E09000014,401.729619,40.0,175.0,314.0,500.0,1100.0,430.122088,0.239607,111.394666,...,2108494,268251.0,134472.0,133779.0,60298.0,182741.0,25212.0,34.982777,29.60,9062.533784
14,E09000015,427.891938,40.0,180.0,325.0,500.0,1400.0,581.035689,0.307016,133.105977,...,2651032,246818.0,122713.0,124105.0,57186.0,152725.0,36907.0,38.037607,50.42,4895.239984
15,E09000016,319.155687,29.0,125.0,239.2,400.0,1000.0,390.140389,0.683918,99.909387,...,421583,249375.0,119743.0,129632.0,54279.0,149202.0,45894.0,40.051188,112.44,2217.849520
16,E09000017,374.737951,36.0,165.0,300.0,500.0,1000.0,394.154178,0.310364,119.792570,...,1168640,296056.0,147929.0,148127.0,70644.0,186478.0,38934.0,36.372359,115.71,2558.603405
17,E09000018,336.922944,32.5,150.0,250.0,450.0,1000.0,359.841786,0.635360,105.201811,...,365032,266412.0,134797.0,131615.0,62349.0,173737.0,30326.0,35.741397,55.95,4761.608579
18,E09000019,357.452740,35.0,155.0,290.0,450.0,1000.0,358.953932,0.273364,104.540991,...,1535553,227507.0,113683.0,113824.0,40109.0,167416.0,19982.0,34.484174,14.90,15268.926174
19,E09000020,372.608765,40.0,170.0,300.0,500.0,1000.0,359.153513,0.280077,100.566629,...,1279530,158589.0,78878.0,79711.0,28328.0,107647.0,22614.0,38.888473,12.11,13095.706028
20,E09000021,297.379174,30.0,125.0,220.0,400.0,1000.0,318.095793,0.996035,95.006632,...,145265,171609.0,84301.0,87308.0,37534.0,111139.0,22936.0,37.072461,37.26,4605.716586
21,E09000022,397.096905,40.0,174.0,300.0,500.0,1100.0,432.868643,0.215760,103.518902,...,2827972,320736.0,160869.0,159867.0,62418.0,233025.0,25293.0,34.320120,26.82,11958.836689
22,E09000023,399.181910,38.0,170.0,302.0,500.0,1160.0,438.427842,0.233233,105.628372,...,2612931,294999.0,144943.0,150056.0,67332.0,200119.0,27548.0,34.885311,35.17,8387.802104
23,E09000024,336.747006,32.0,150.0,250.0,440.0,1000.0,360.640133,0.407096,103.753813,...,923444,205965.0,101313.0,104652.0,46260.0,134778.0,24927.0,36.593164,37.64,5471.971307
24,E09000025,450.349903,39.0,175.0,325.0,500.0,1500.0,718.157462,0.386833,136.703561,...,2839005,336254.0,176602.0,159652.0,83982.0,228855.0,23417.0,32.038272,36.21,9286.219276
25,E09000026,407.369285,37.0,170.0,300.0,500.0,1200.0,556.091738,0.441890,119.013556,...,1112166,297928.0,148700.0,149228.0,75418.0,186229.0,36281.0,35.736752,56.38,5284.285208
26,E09000027,321.808045,32.5,150.0,250.0,405.0,1000.0,300.762891,0.516371,97.373183,...,357840,194124.0,94288.0,99836.0,44364.0,120918.0,28842.0,38.726402,57.40,3381.951220
27,E09000028,387.681320,40.0,175.0,300.0,500.0,1000.0,393.486213,0.178711,107.157266,...,3560276,308434.0,153470.0,154964.0,62902.0,221000.0,24532.0,34.200656,28.86,10687.248787
28,E09000029,295.330271,28.0,120.0,215.0,400.0,1000.0,345.190175,0.891018,98.495864,...,234609,199870.0,97427.0,102443.0,46142.0,123600.0,30128.0,38.449162,43.80,4563.242009
29,E09000030,390.047012,37.5,160.0,300.0,500.0,1000.0,506.511927,0.278470,112.608969,...,2707571,293828.0,152762.0,141066.0,64797.0,211354.0,17677.0,31.514726,19.75,14877.367089
30,E09000031,414.805726,40.0,180.0,320.0,500.0,1280.0,510.104074,0.216160,117.975457,...,3441950,270671.0,135651.0,135020.0,65030.0,177768.0,27873.0,34.990623,38.86,6965.285641
31,E09000032,350.286873,35.0,150.0,268.0,450.0,1000.0,378.044382,0.313651,103.653029,...,1377019,319477.0,154118.0,165359.0,61036.0,229044.0,29397.0,34.811996,34.25,9327.795620
32,E09000033,380.470120,40.0,165.0,300.0,500.0,1000.0,428.667556,0.327936,107.933971,...,1485336,238047.0,123356.0,114691.0,42610.0,167188.0,28249.0,37.157952,21.50,11071.953488

In [3]:
# Prepare data to extract INSIGHT 1 from TESCO 1.0 dataset

# # Disable warning
# pandas.set_option("mode.chained_assignment", None)

# Get data
area_population_borough = annual_data_groceriespurchased_borough.copy()

# Calculate gender different ratio for plotting graph
area_population_borough["gender_majority"] = numpy.where(area_population_borough["male"] > area_population_borough["female"], "male", \
                                                         numpy.where(area_population_borough["male"] < area_population_borough["female"], "female", "equal"))
area_population_borough["male_percentage"] = (area_population_borough["male"] * 100) / area_population_borough["population"]
area_population_borough["female_percentage"] = (area_population_borough["female"] * 100) / area_population_borough["population"]
area_population_borough["gender_diff"] = area_population_borough["male_percentage"] - area_population_borough["female_percentage"]

# Remove unused columns
insight_1_cols = ["area_id", "f_beer", "f_dairy", "f_eggs", "f_fats_oils", "f_fish", "f_fruit_veg", "f_grains", "f_meat_red", "f_poultry", \
                  "f_readymade", "f_sauces", "f_soft_drinks", "f_spirits", "f_sweets", "f_tea_coffee", "f_water", "f_wine", \
                  "gender_majority", "male_percentage", "female_percentage", "gender_diff"]
area_population_borough.drop(area_population_borough.columns.difference(insight_1_cols), axis = 1, inplace = True)

# Select male top 5 and female top 5 areas
area_population_borough_maletop5 = area_population_borough.sort_values("male_percentage",ascending = False).head(5)
area_population_borough_femaletop5 = area_population_borough.sort_values("female_percentage",ascending = False).head(5)
area_population_borough_bothtop5 = area_population_borough_maletop5.append(area_population_borough_femaletop5, ignore_index=True)

# Display data
display(area_population_borough_bothtop5)
area_population_borough_bothtop5.to_csv(folder_path + "year_borough_grocery_addedpop.csv", index = False, header = True)

,area_id,f_beer,f_dairy,f_eggs,f_fats_oils,f_fish,f_fruit_veg,f_grains,f_meat_red,f_poultry,...,f_soft_drinks,f_spirits,f_sweets,f_tea_coffee,f_water,f_wine,gender_majority,male_percentage,female_percentage,gender_diff
0,E09000001,0.026307,0.121101,0.011756,0.022851,0.021307,0.322872,0.122289,0.046465,0.018064,...,0.021961,0.003293,0.139697,0.004958,0.022606,0.025985,male,55.286377,44.713623,10.572753
1,E09000025,0.012108,0.114938,0.013791,0.037930,0.019768,0.254554,0.154189,0.042994,0.017083,...,0.035121,0.003464,0.177719,0.005646,0.040647,0.008702,male,52.520416,47.479584,5.040832
2,E09000030,0.013757,0.105041,0.012604,0.030400,0.024498,0.280080,0.144193,0.046298,0.018879,...,0.029119,0.002511,0.172321,0.005362,0.031980,0.013576,male,51.990280,48.009720,3.980560
3,E09000033,0.011484,0.125235,0.015223,0.030723,0.024516,0.314086,0.133382,0.041930,0.018919,...,0.021308,0.002437,0.147929,0.005990,0.031305,0.017781,male,51.820019,48.179981,3.640037
4,E09000005,0.010729,0.115018,0.012938,0.032990,0.020180,0.270670,0.157685,0.046171,0.020670,...,0.031545,0.003703,0.161408,0.005914,0.037473,0.011597,male,50.685592,49.314408,1.371184
5,E09000016,0.012316,0.087824,0.007310,0.020587,0.016579,0.240151,0.174518,0.043582,0.019507,...,0.034791,0.003048,0.188978,0.006588,0.028724,0.012160,female,48.017243,51.982757,-3.965514
6,E09000006,0.019327,0.096956,0.008775,0.023215,0.016209,0.247085,0.164548,0.042790,0.017570,...,0.035204,0.003032,0.179765,0.005713,0.028668,0.020766,female,48.039520,51.960480,-3.920960
7,E09000004,0.012231,0.095073,0.008948,0.025275,0.017349,0.251681,0.170318,0.046667,0.020140,...,0.031980,0.003100,0.172936,0.006770,0.031482,0.012945,female,48.193179,51.806821,-3.613643
8,E09000032,0.018823,0.108012,0.012962,0.027796,0.023020,0.294629,0.141700,0.047304,0.020967,...,0.027503,0.003164,0.146673,0.005410,0.027491,0.022600,female,48.240718,51.759282,-3.518563
9,E09000008,0.014641,0.099640,0.009745,0.025935,0.018104,0.247149,0.161678,0.044945,0.019698,...,0.039888,0.003607,0.172795,0.006453,0.037988,0.015095,female,48.492383,51.507617,-3.015234

In [5]:
# Prepare data to extract INSIGHT 2 from TESCO 1.0 dataset

# Get data
fruitnveg_borough = annual_data_groceriespurchased_borough.copy()

# Remove unused columns
insight_2_cols = ["area_id", "f_beer", "f_dairy", "f_eggs", "f_fats_oils", "f_fish", "f_fruit_veg", "f_grains", "f_meat_red", "f_poultry", \
                  "f_readymade", "f_sauces", "f_soft_drinks", "f_spirits", "f_sweets", "f_tea_coffee", "f_water", "f_wine"]
fruitnveg_borough.drop(fruitnveg_borough.columns.difference(insight_2_cols), axis = 1, inplace = True)

# Select top 5 and bottom 5 areas
fruitnveg_borough_top5 = fruitnveg_borough.sort_values("f_fruit_veg",ascending = False).head(5)
fruitnveg_borough_bottom5 = fruitnveg_borough.sort_values("f_fruit_veg",ascending = True).head(5)
fruitnveg_borough = fruitnveg_borough_top5.append(fruitnveg_borough_bottom5, ignore_index=True)
fruitnveg_borough = fruitnveg_borough.sort_values("f_fruit_veg",ascending = False, ignore_index=True)

# Display data
display(fruitnveg_borough)
fruitnveg_borough.to_csv(folder_path + "year_borough_grocery_fruitnveg.csv", index = False, header = True)

,area_id,f_beer,f_dairy,f_eggs,f_fats_oils,f_fish,f_fruit_veg,f_grains,f_meat_red,f_poultry,f_readymade,f_sauces,f_soft_drinks,f_spirits,f_sweets,f_tea_coffee,f_water,f_wine
0,E09000020,0.013193,0.114340,0.015261,0.032042,0.028689,0.333247,0.125741,0.048621,0.020861,0.046951,0.013302,0.020446,0.003350,0.128020,0.005946,0.026935,0.023054
1,E09000003,0.011298,0.106467,0.012773,0.032430,0.024277,0.327326,0.132781,0.050390,0.020199,0.048065,0.014555,0.023797,0.003019,0.141607,0.006141,0.029242,0.015634
2,E09000001,0.026307,0.121101,0.011756,0.022851,0.021307,0.322872,0.122289,0.046465,0.018064,0.057108,0.011381,0.021961,0.003293,0.139697,0.004958,0.022606,0.025985
3,E09000007,0.016162,0.117740,0.012189,0.027497,0.023463,0.321332,0.130472,0.043330,0.018664,0.053354,0.012865,0.022920,0.002551,0.142966,0.005284,0.025420,0.023789
4,E09000013,0.014095,0.110326,0.013749,0.031538,0.028037,0.321305,0.129188,0.054153,0.021460,0.050061,0.015214,0.021908,0.002637,0.134443,0.005430,0.025855,0.020601
5,E09000002,0.010783,0.096583,0.011266,0.031448,0.020717,0.248116,0.157618,0.051076,0.020254,0.061959,0.014344,0.037077,0.003822,0.179794,0.006770,0.039458,0.008913
6,E09000008,0.014641,0.099640,0.009745,0.025935,0.018104,0.247149,0.161678,0.044945,0.019698,0.068986,0.013652,0.039888,0.003607,0.172795,0.006453,0.037988,0.015095
7,E09000006,0.019327,0.096956,0.008775,0.023215,0.016209,0.247085,0.164548,0.042790,0.017570,0.077219,0.013160,0.035204,0.003032,0.179765,0.005713,0.028668,0.020766
8,E09000029,0.015258,0.092498,0.007614,0.017709,0.013960,0.244251,0.175507,0.036044,0.016270,0.092750,0.010719,0.037453,0.003447,0.188155,0.005490,0.027990,0.014886
9,E09000016,0.012316,0.087824,0.007310,0.020587,0.016579,0.240151,0.174518,0.043582,0.019507,0.090930,0.012406,0.034791,0.003048,0.188978,0.006588,0.028724,0.012160

In [6]:
# REGIONAL GROSS DISPOSABLE HOUSEHOLD INCOME DATASET

# Declare vars
folder_path = "/Users/rasitapkr/Documents/MSc Data Science/Applied Data Science/Coursework Sem 2/Datasets/"

# Get annual data from file and add to dataframe
income_borough = pandas.DataFrame([])
income_borough_file = pandas.ExcelFile(folder_path + "regionalgrossdisposablehouseholdincomelocalauthoritytlilondon2020.xls")
income_borough = pandas.read_excel(income_borough_file, "Table 2", skiprows=[0])
income_borough = income_borough.sort_values("LAD code",ascending = True, ignore_index=True)
display(income_borough)

,Region,LAD code,Region name,1997,1998,1999,2000,2001,2002,2003,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,London,E09000001,City of London,90955,100333,93408,99183,97691,99214,104460,...,148259,179835,218893,226637,227911,217301,214667,208106,179272,147813
1,London,E09000002,Barking and Dagenham,8842,9089,9510,9999,10657,11049,11713,...,14348,15106,15353,15565,16270,16625,17003,18148,18832,19265
2,London,E09000003,Barnet,12615,13265,13976,15155,15672,16163,16923,...,21570,23076,24030,25271,28080,28717,29068,30624,31136,30460
3,London,E09000004,Bexley,11663,11776,12247,12888,13708,14012,14535,...,17945,18870,19418,19881,21207,21760,21897,23001,23790,23758
4,London,E09000005,Brent,10784,11226,12065,12904,13436,13966,14638,...,18501,19853,21043,21911,23510,23724,24089,25650,26226,26438
5,London,E09000006,Bromley,13808,14431,15174,16289,16824,17136,18067,...,22622,23912,24614,25618,27424,27690,27734,29385,30025,29854
6,London,E09000007,Camden,16075,17822,19004,21065,20960,20976,21301,...,31706,34063,37391,37995,40397,40774,41510,44243,44009,41810
7,London,E09000008,Croydon,10174,10553,11344,12346,12946,13386,14142,...,17981,19012,19657,19959,21498,21855,22254,23846,24676,24636
8,London,E09000009,Ealing,12886,13217,13953,14767,15324,15695,16421,...,20258,21674,23008,24276,26253,26354,26409,27477,28128,28337
9,London,E09000010,Enfield,10853,11228,11604,12564,13313,13446,13996,...,17558,18708,19147,19849,21461,21969,22037,23094,24105,24188
10,London,E09000011,Greenwich,13728,13786,14438,15197,15751,15841,16258,...,18748,19317,20021,20565,21621,22039,22270,23384,24424,24761
11,London,E09000012,Hackney,7273,7980,8818,9987,10573,10910,11343,...,17549,18506,19936,20742,22507,23203,23437,24670,25852,25952
12,London,E09000013,Hammersmith and Fulham,21077,21234,22403,24194,24179,23595,24404,...,32539,34811,38925,41268,42654,41819,42608,44109,43730,43998
13,London,E09000014,Haringey,13974,14243,15164,16162,16501,16715,17062,...,22396,23820,24325,25370,27028,26523,27625,29024,30049,30099
14,London,E09000015,Harrow,12769,13473,14213,15241,15879,16346,17059,...,20513,21905,23193,23970,25845,26406,26808,28292,28374,27854
15,London,E09000016,Havering,11207,11662,12107,13106,13892,14193,14727,...,18337,19407,20028,20262,21725,22298,22551,23838,24274,24055
16,London,E09000017,Hillingdon,10279,10764,11614,12429,13150,13628,14380,...,17894,18873,19770,20016,21485,21921,22063,22953,23688,23621
17,London,E09000018,Hounslow,14207,14442,15128,15911,16443,16757,17541,...,19608,20855,21769,22403,24143,23758,24139,25684,26684,26951
18,London,E09000019,Islington,16617,16769,18299,19601,20003,20416,20739,...,27059,28345,28811,29585,31199,30669,30741,32300,33261,32756
19,London,E09000020,Kensington and Chelsea,34846,34560,35735,38233,37352,36662,37258,...,56104,62152,68981,74087,77467,76952,78689,84897,82283,79325
20,London,E09000021,Kingston upon Thames,14471,14670,15409,16489,16803,16995,17665,...,21409,22606,23436,23735,25073,25396,25309,27550,27532,26963
21,London,E09000022,Lambeth,11041,11344,12339,13477,13739,13972,14418,...,19820,20920,21864,22836,25844,27077,27151,29092,30035,30386
22,London,E09000023,Lewisham,8727,9049,9830,10707,11151,11441,12089,...,17255,18286,19050,19937,21329,21718,22463,23652,24762,24991
23,London,E09000024,Merton,15972,16388,17205,18294,18622,19004,19917,...,25009,26347,27720,28635,30517,30954,31024,33008,34422,34102
24,London,E09000025,Newham,5561,6083,6839,7839,8400,8704,9436,...,13552,14210,14872,15148,16462,17034,17813,18996,19946,20102
25,London,E09000026,Redbridge,11347,11580,12043,12933,13641,13941,14319,...,17148,18247,18639,19078,20826,21119,21904,23508,23808,23865
26,London,E09000027,Richmond upon Thames,21361,21769,22639,24257,24618,24775,25295,...,31752,33906,35578,36885,39980,39187,39495,42504,43400,43037
27,London,E09000028,Southwark,11155,11605,12455,13532,13813,14060,14703,...,19924,20975,21886,23090,24677,25048,25585,27540,28014,27878
28,London,E09000029,Sutton,12041,12406,13082,14118,14531,14812,15463,...,19389,20518,21261,21547,23062,23448,23441,24961,25534,25227
29,London,E09000030,Tower Hamlets,13130,13348,14069,15107,15526,15546,16026,...,20344,21161,21749,22095,23598,24474,24602,25629,26246,26175
30,London,E09000031,Waltham Forest,10594,10801,11470,12209,13156,13554,14193,...,17209,18394,19149,19841,21504,22080,22891,24304,25278,25486
31,London,E09000032,Wandsworth,13802,15350,17080,19253,19833,19741,20120,...,28077,29987,32826,34708,36632,37589,37794,39853,40665,40793
32,London,E09000033,Westminster,20955,21757,23748,25781,26160,25842,26303,...,39513,42779,46942,49486,52695,53894,53729,54284,52926,48382

In [7]:
# Prepare data to extract INSIGHT from both datasets

# Get income 2015 data
income_borough_2015 = income_borough.copy()
insight_both_cols = ["LAD code", "2015"]
income_borough_2015.drop(income_borough_2015.columns.difference(insight_both_cols), axis = 1, inplace = True)

# Convert income to represent in 100K
income_borough_2015["2015 in 100K"] = income_borough_2015["2015"] / 100000
# display(income_borough_2015)

# Combine 2 datasets together
two_datasets = annual_data_groceriespurchased_borough.merge(income_borough_2015, left_on="area_id", right_on="LAD code")
insight_both_cols = ["area_id", "f_fruit_veg", "2015 in 100K"]
two_datasets.drop(two_datasets.columns.difference(insight_both_cols), axis = 1, inplace = True)
display(two_datasets)

# Export
two_datasets.to_csv(folder_path + "year_borough_grocery_withincome.csv", index = False, header = True)

      area_id  f_fruit_veg  2015 in 100K
0   E09000001     0.322872       2.27911
1   E09000002     0.248116       0.16270
2   E09000003     0.327326       0.28080
3   E09000004     0.251681       0.21207
4   E09000005     0.270670       0.23510
5   E09000006     0.247085       0.27424
6   E09000007     0.321332       0.40397
7   E09000008     0.247149       0.21498
8   E09000009     0.303364       0.26253
9   E09000010     0.265979       0.21461
10  E09000011     0.265657       0.21621
11  E09000012     0.281518       0.22507
12  E09000013     0.321305       0.42654
13  E09000014     0.288085       0.27028
14  E09000015     0.293165       0.25845
15  E09000016     0.240151       0.21725
16  E09000017     0.278668       0.21485
17  E09000018     0.285183       0.24143
18  E09000019     0.296634       0.31199
19  E09000020     0.333247       0.77467
20  E09000021     0.267838       0.25073
21  E09000022     0.291618       0.25844
22  E09000023     0.272404       0.21329
23  E09000024     0.286429       0.30517
24  E09000025     0.254554       0.16462
25  E09000026     0.270529       0.20826
26  E09000027     0.309740       0.39980
27  E09000028     0.291334       0.24677
28  E09000029     0.244251       0.23062
29  E09000030     0.280080       0.23598
30  E09000031     0.272257       0.21504
31  E09000032     0.294629       0.36632
32  E09000033     0.314086       0.52695